language: cpp
sudo: false
  
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['liblog4cxx10-dev','libboost-program-options-dev','libboost-filesystem-dev','libboost-date-time-dev','libboost-system-dev','libboost-test-dev','libboost-thread-dev','libzmq3-dev']
      env: PYTHONPATH=./lib/python FR_TEST_CONFIG=test_config/fr_test.config FP_TEST_CONFIG=test_config/fp_test.config

    - os: osx
      osx_image: xcode7
      compiler: clang
      before_install: brew update || brew update && brew install cmake log4cxx boost zeromq python
      env: PYTHONPATH=./lib/python FR_TEST_CONFIG=test_config/fr_test_osx.config FP_TEST_CONFIG=test_config/fp_test_osx.config

install:
  - mkdir -p build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - pip install --user -r $PYTHONPATH/requirements.txt

script:
  - bin/frameReceiverTest --log_level=all
  - python bin/run_integration_test.py --frames=1 --interval=1.0 --timeout=30 --fr_config=$FR_TEST_CONFIG --fp_config=$FP_TEST_CONFIG

notifications:
  slack:
    secure: r8pM4/MZxsJrazTV/mm6WF/qUb+Kz6rOnmNtCS3ggHthH4ISkks9hGGY055cOG3F0AUBzLimPttYFwAn9uPLxTr2VCWUZ9Bx5q4CAILspmzYTJcbFDG+vyiyJEw5b2DzaXto9wcvRMNx5UDGlXXygEvBwpEV7Mgh2jR9jEQKGds=
