language: cpp
sudo: false
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        packages:
        - liblog4cxx10-dev
        - libboost-program-options-dev
        - libboost-filesystem-dev
        - libboost-date-time-dev
        - libboost-system-dev
        - libboost-test-dev
        - libboost-thread-dev
        - libzmq3-dev
    env: PYTHONPATH=./lib/python FR_TEST_CONFIG=test_config/fr_test.config FP_TEST_CONFIG=test_config/fp_test.config
      HDF5_ROOT=$HOME/hdf5-1.8.16
    before_install:
    - bash .travis-install-hdf5.sh
    cache:
      directories:
      - "$HOME/hdf5-1.8.16"
install:
- mkdir -p build
- cd build
- cmake -DHDF5_ROOT=$HDF5_ROOT ..
- make -j 4 VERBOSE=1
- HDF5_DIR=$HDF5_ROOT pip install --user h5py
- pip install --user -r $PYTHONPATH/requirements-travis.txt
script:
- bin/frameReceiverTest --log_level=all
- bin/frameProcessorTest --log_level=all
notifications:
  slack:
    secure: brPUW4TCnMf3qFpBF+zc+AgFYgfUmPRoXOya7u1ByTV5414tFiKi/uAF70GhE903DG6J1SSp8nxmSdanFs2gts03KkfAnrX8ObeA8Osj5QE1XR/X3GLk55oBEj1cgOa77jgTc9FD4mh7WTkH/uGYWQwpl53P5G66kLqnAyt3uwhaf0GN7rkb6m7LKi1zH3NV5Oka/HCyKI538oXKVrUK5xyUZ7w8cwbZUPQ2+gMkIvhYrOr/7r6Hdqg5JzbdDdeDWUta3X3A1Ow0EY9e9GPVVUCFjnq+Oh0M7Qrh6uwNQJ/7h81jeGuKRou2soK69skUUnusbEmhdHKuz3G2L3mrlxlyyBgTR6i0iF++XMfE+qmpWRix64KqDcwaZ/M+s/vfihHwqj+GcjROdsOaPGaza95XYwELVS7OAhLqsa/Xu5a+U8I65K7WqCenA2f3je96Z5q1vyPE1QAVx9Pxf3kr6xue4I6G6LvH4+fbrAUqOY2xhiFC+YULA2WjrUqgrWKrAldfsIGM8u45/PbsDu9/1FIY7NbsNP+lJrzSgVKYaS8DtDVoXbphvoSCecPO4S2McRqYhax3OM9u+ht2ymgCCL1+tBpwYcNLKGAhZwsAX8QRWbG0C9y+jSFP/FC1SFzVR765Cxao9S/AjYjZcLl3rgSC4Sg+of+RLR471IaggwI=
