language: cpp
sudo: false
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        packages:
        - liblog4cxx10-dev
        - libboost-program-options-dev
        - libboost-filesystem-dev
        - libboost-date-time-dev
        - libboost-system-dev
        - libboost-test-dev
        - libboost-thread-dev
        - libzmq3-dev
    env: PYTHONPATH=./lib/python FR_TEST_CONFIG=test_config/fr_test.config FP_TEST_CONFIG=test_config/fp_test.config
      HDF5_ROOT=$HOME/hdf5-1.8.16
    before_install:
    - bash .travis-install-hdf5.sh
    cache:
      directories:
      - "$HOME/hdf5-1.8.16"
install:
- mkdir -p build
- cd build
- cmake -DHDF5_ROOT=$HDF5_ROOT ..
- make -j 4 VERBOSE=1
- HDF5_DIR=$HDF5_ROOT pip install --user h5py
- pip install --user -r $PYTHONPATH/requirements-travis.txt
script:
- bin/frameReceiverTest --log_level=all
- bin/frameProcessorTest --log_level=all
notifications:
  slack:
    secure: A+FovIpo1X/10EOCydCh0xkZ/0YZNeE4OVmIFGpC27hSxHvu7IkXNYsg1v21izwMixMJCoIfskjvSnGKveMrk6iigWfa6GlzB4cj8KW1O8zOnb3/ZdHhMeDqUyJNezNjJtIcjR1fuVB1XlSyP8UiDnoZ0lRew2GY7D/2/TLmMfNNiwADiQ3+a6LI0Cet4uQEyM+HDx+rHhOv4ivwOoaY7atiV6Fu/YwZYz/i7vmonAL0ekkQ+aDSUGMWooEl5g95EM28TbVkZzJZ6IB8v3KV/QQWdAlnzpE3ELbJ2taVf/Ffdsn3oC+Zuz/3RJYoKyzDpfqGO6akOiFXRc6WP0wEvtaxrGhwBtGnOE8N/7k+lLr9DszNDf866RilCvJgtn+WFkuVsc6w1k9cDCwyBFiAC05S8et6hmiCpQ7SPEv3RPlEWXghRCownVXdnDS9IsXv/eYrdXqRSxBZy3OQ36gFB8txMliBvj6F5muDwqMepgoiQVICk2BFojeEu7DActDibcxs9l59vHgMszsLjzzZK5tzMPMl/TLmaXH1fPOf5h2hAdHNcU2nZ+qLfU+k9ovwpEZDkq6qWRUOF9mBrtP7tNJ/M/CZuhXdb5UO7qwTiGzmhKXiaIFd2W/E4LmuoXnkAToPwJC210/T9gsYF7V5cPVX17dDR6jUoqZZ4g8Yes0=
